#use_frameworks!
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.dev.zhaopin.com/Mobile/ios-common-index.git'

target 'WLRRoute_Example' do
  pod 'ZPMRoute', :path => '../'
  pod 'SVProgressHUD'
  pod 'ZPMNetwork'
  
  target 'WLRRoute_Tests' do
    inherit! :search_paths

    
  end
end
